[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install", "cd src/client && npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
